version: '2'

services:
    postgres:
        image: postgres:11.5
        ports:
            - "5440:5432"
        restart: always
        volumes:
            - $PWD/tests/database/dump:/docker-entrypoint-initdb.d/
        environment:
            - "POSTGRES_DB=projeto"
            - "POSTGRES_USER=projeto"
            - "POSTGRES_PASSWORD=mysecretpassword"